Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-05, with the labels that each got.

#61 [Travis] Changed ezplatform-kernel notification key after rebranding
  .travis.yml
Labels: Fast-forward merge

#60 [Tests] Fixed obsolete PHPUnit class names
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/ProxyResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/RelativeResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/ResolverFactoryTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/ImageAsset/AliasGeneratorTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorTest.php
  eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/Core/FieldType/Tests/ImageAsset/AssetMapperTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/SPI/FieldType/Tests/FieldTypeTest.php
Labels: Improvement, Ready for review

#65 [Composer] Restored required Behat dev dependencies
  composer.json
Labels: Bug, Ready for review

#64 [Symfony] Dropped obsolete Composer ScriptHandler
  eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
Labels: Bug

#56 EZP-31590: Added update feature for URL Wildcards
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Publish/API/Repository/Events/URLWildcard/BeforeUpdateEvent.php
  eZ/Publish/API/Repository/Events/URLWildcard/UpdateEvent.php
  eZ/Publish/API/Repository/Tests/URLWildcardServiceTest.php
  eZ/Publish/API/Repository/URLWildcardService.php
  eZ/Publish/API/Repository/Values/Content/URLWildcardStruct.php
  eZ/Publish/API/Repository/Values/Content/URLWildcardUpdateStruct.php
  eZ/Publish/Core/Event/Tests/URLWildcardServiceTest.php
  eZ/Publish/Core/Event/URLWildcardService.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlWildcardHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlWildcardHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/UrlWildcardHandlerTest.php
  eZ/Publish/Core/Repository/URLWildcardService.php
  eZ/Publish/SPI/Persistence/Content/UrlWildcard/Handler.php
  eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php
Labels: QA approved
