Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-04, with the labels that each got.

#30 EZP-31012: Fixed conversion to persistence value in ezuser field type (empty passwordUpdateAt)
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/FieldType/User/Type.php
Labels: Bug, QA approved

#17 EZP-31527: Changed ProgressBar of ezplatform:reindex command to be very verbose
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Improvement, QA approved

#31 Moved upgrade scripts to eZ Platform meta repository
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
  data/update/README.md
  data/update/mysql/dbupdate-5.4.0-to-6.13.0.sql
  data/update/mysql/dbupdate-5.4.0-to-6.4.0.sql
  data/update/mysql/dbupdate-6.1.0-to-6.4.0.sql
  data/update/mysql/dbupdate-6.10.0-to-6.11.0.sql
  data/update/mysql/dbupdate-6.11.0-to-6.12.0.sql
  data/update/mysql/dbupdate-6.13.3-to-6.13.4.sql
  data/update/mysql/dbupdate-6.3.0-to-6.4.0.sql
  data/update/mysql/dbupdate-6.5.0-to-6.6.0.sql
  data/update/mysql/dbupdate-6.7.0-to-6.8.0.sql
  data/update/mysql/dbupdate-6.7.7-to-6.7.8.sql
  data/update/mysql/dbupdate-7.1.0-to-7.2.0-dfs.sql
  data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
  data/update/mysql/dbupdate-7.2.0-to-7.3.0.sql
  data/update/mysql/dbupdate-7.4.0-to-7.5.0.sql
  data/update/mysql/dbupdate-7.4.4-to-7.4.5.sql
  data/update/mysql/dbupdate-7.5.2-to-7.5.3.sql
  data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql
  data/update/mysql/dbupdate-7.5.6-to-7.5.7.sql
  data/update/mysql/dbupdate-7.5.latest-to-8.0.0.sql
  data/update/mysql/unstable/dbupdate-5.4.0-to-6.0.0alpha7.sql
  data/update/mysql/unstable/dbupdate-6.0.0-to-6.1.0rc1.sql
  data/update/mysql/unstable/dbupdate-6.0.0alpha7-to-6.0.0beta1.sql
  data/update/mysql/unstable/dbupdate-6.1.0-to-6.2.0rc1.sql
  data/update/mysql/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql
  data/update/postgres/dbupdate-5.4.0-to-6.13.0.sql
  data/update/postgres/dbupdate-5.4.0-to-6.4.0.sql
  data/update/postgres/dbupdate-6.10.0-to-6.11.0.sql
  data/update/postgres/dbupdate-6.11.0-to-6.12.0.sql
  data/update/postgres/dbupdate-6.13.3-to-6.13.4.sql
  data/update/postgres/dbupdate-6.3.0-to-6.4.0.sql
  data/update/postgres/dbupdate-6.5.0-to-6.6.0.sql
  data/update/postgres/dbupdate-6.7.0-to-6.8.0.sql
  data/update/postgres/dbupdate-6.7.7-to-6.7.8.sql
  data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql
  data/update/postgres/dbupdate-7.2.0-to-7.3.0.sql
  data/update/postgres/dbupdate-7.4.0-to-7.5.0.sql
  data/update/postgres/dbupdate-7.5.2-to-7.5.3.sql
  data/update/postgres/dbupdate-7.5.4-to-7.5.5.sql
  data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql
  data/update/postgres/dbupdate-7.5.latest-to-8.0.0.sql
  data/update/postgres/unstable/dbupdate-5.4.0-to-6.0.0alpha7.sql
  data/update/postgres/unstable/dbupdate-6.0.0-to-6.1.0rc1.sql
  data/update/postgres/unstable/dbupdate-6.0.0alpha7-to-6.0.0beta1.sql
  data/update/postgres/unstable/dbupdate-6.1.0-to-6.2.0rc1.sql
  data/update/postgres/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql
Labels: Improvement, Ready for review

#19 EZP-31529: Added --no-interaction option to cmd regenerating URL aliases
  eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
Labels: QA approved

#32 EZP-31519: Move app.php rejection snippet from front controller to ezpublish-kernel
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/RejectExplicitFrontControllerRequestsListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/http_kernel.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RejectExplicitFrontControllerRequestsListenerTest.php
Labels: Improvement, QA approved, Ready for review

#33 EZP-31536: Fixed cache corruption for the ez-users-<email>-by-email key
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
Labels: Bug

#35 EZP-30543: Removed Dynamic Settings functionality from kernel
  doc/bc/changes-1.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ComplexSettingsPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ConfigResolverParameterPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/CacheViewResponseListener.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/DynamicSettingsListener.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/VariationPurger/LegacyStorageImageFileList.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/url_checker.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ComplexSettingsPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ConfigResolverParameterPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/DynamicSettingsListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/VariationPurger/LegacyStorageImageFileListTest.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/AbstractConfigResolverBasedURLHandler.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/AbstractURLHandler.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/HTTPHandler.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/MailToHandler.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/URLHandlerInterface.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/Factory/LocalAdapterFactory.php
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Publish/Core/FieldType/Image/IO/OptionsProvider.php
  eZ/Publish/Core/FieldType/ImageAsset/AssetMapper.php
  eZ/Publish/Core/FieldType/Tests/Image/IO/LegacyTest.php
  eZ/Publish/Core/FieldType/Tests/ImageAsset/AssetMapperTest.php
  eZ/Publish/Core/IO/Adapter/LocalAdapter.php
  eZ/Publish/Core/IO/ConfigScopeChangeAwareIOService.php
  eZ/Publish/Core/IO/IOBinarydataHandler/SiteAccessDependentBinaryDataHandler.php
  eZ/Publish/Core/IO/IOBinarydataHandler/SiteAccessDependentMetadataHandler.php
  eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadController.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FieldRenderingExtensionIntegrationTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/ResourceProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/ResourceProvider.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/ResourceProviderInterface.php
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/SPI/MVC/EventSubscriber/ConfigScopeChangeSubscriber.php
  eZ/Publish/SPI/Tests/FieldType/ImageAssetIntegrationTest.php
Labels: Improvement, Ready for review

#11 EZP-30921: Dropped deprecated eZc database abstraction layer
  doc/bc/changes-1.0.md
  eZ/Bundle/EzPublishCoreBundle/Imagine/VariationPurger/LegacyStorageImageFileRowReader.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage_engines.yml
  eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageFileRowReader.php
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Publish/Core/FieldType/Tests/Integration/BaseCoreFieldTypeIntegrationTest.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/Gateway/DoctrineStorageTest.php
  eZ/Publish/Core/Persistence/Database/DatabaseHandler.php
  eZ/Publish/Core/Persistence/Database/DeleteQuery.php
  eZ/Publish/Core/Persistence/Database/Expression.php
  eZ/Publish/Core/Persistence/Database/InsertQuery.php
  eZ/Publish/Core/Persistence/Database/Query.php
  eZ/Publish/Core/Persistence/Database/QueryException.php
  eZ/Publish/Core/Persistence/Database/SelectQuery.php
  eZ/Publish/Core/Persistence/Database/UpdateQuery.php
  eZ/Publish/Core/Persistence/Doctrine/AbstractDoctrineQuery.php
  eZ/Publish/Core/Persistence/Doctrine/ConnectionHandler.php
  eZ/Publish/Core/Persistence/Doctrine/ConnectionHandler/PostgresConnectionHandler.php
  eZ/Publish/Core/Persistence/Doctrine/ConnectionHandler/SqliteConnectionHandler.php
  eZ/Publish/Core/Persistence/Doctrine/DeleteDoctrineQuery.php
  eZ/Publish/Core/Persistence/Doctrine/DoctrineExpression.php
  eZ/Publish/Core/Persistence/Doctrine/InsertDoctrineQuery.php
  eZ/Publish/Core/Persistence/Doctrine/SelectDoctrineQuery.php
  eZ/Publish/Core/Persistence/Doctrine/SubselectDoctrineQuery.php
  eZ/Publish/Core/Persistence/Doctrine/UpdateDoctrineQuery.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php
  eZ/Publish/Core/Persistence/Legacy/EzcDbHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TransactionHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/LimitationConverterTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/TransactionHandler.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/LimitationHandler.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/LimitationHandler/ObjectStateHandler.php
  eZ/Publish/Core/Persistence/Legacy/docs/architecture.txt
  eZ/Publish/Core/settings/search_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/external_storage_gateways.yml
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_criterion_handlers.yml
  eZ/Publish/Core/settings/storage_engines/legacy/user.yml
  eZ/Publish/SPI/FieldType/FieldStorage.php
  eZ/Publish/SPI/FieldType/StorageGateway.php
  eZ/Publish/SPI/Tests/FieldType/MapLocationIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/RelationListIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/UrlIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
  phpunit.xml
Labels: Improvement, Ready for QA, Ready for review

#39 EZP-31544: changed $configResolver from private to protected and changed variable
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/AbstractConfigResolverBasedURLHandler.php
  eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/HTTPHandler.php
Labels: Bug, QA approved

#41 EZEE-3091: Used twig dump to display object arguments
  composer.json
  eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/panel.html.twig
Labels: QA approved

#43 EZP-30465: Fixed PermissionResolver injection into commands
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: Bug, QA approved

#38 EZP-31546: Fixed ignored path prefixes for binaries and images
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Publish/Core/IO/ConfigScopeChangeAwareIOService.php
  eZ/Publish/Core/IO/Tests/ConfigScopeChangeAwareIOServiceTest.php
Labels: Bug, Ready for review

#42 EZP-31281: Decoupled RoleDomainMapper from Repository
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Helper/Tests/ContentInfoLocationLoader/SudoMainLocationLoaderTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/BaseTest.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
  eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
  eZ/Publish/Core/Repository/Mapper/RoleDomainMapper.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/RoleService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RoleTest.php
  eZ/Publish/Core/settings/repository/inner.yml
Labels: Improvement, Ready for MERGE, Ready for review

#49 EZP-31580: Fixed injection of User Handler into PermissionResolver
  eZ/Publish/Core/settings/repository/inner.yml
Labels: Bug, QA approved

#47 EZEE-3085: Added specification ContentTypeSpecification
  eZ/Publish/SPI/Specification/Content/ContentContainerSpecification.php
  eZ/Publish/SPI/Specification/Content/ContentSpecification.php
  eZ/Publish/SPI/Specification/Content/ContentTypeSpecification.php
  eZ/Publish/SPI/Specification/Tests/Content/ContentContainerSpecificationTest.php
  eZ/Publish/SPI/Specification/Tests/Content/ContentTypeSpecificationTest.php
Labels: QA approved

#52 EZP-31591: Farsi (Persian) language is missing in internal locale conversion map
  eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
  eZ/Publish/Core/MVC/Symfony/Locale/LocaleConverterInterface.php
Labels: QA approved
