Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-08, with the labels that each got.

#95 EZP-31789: Fixed invalid array type returned for getFieldErrors
  eZ/Publish/Core/Repository/Strategy/ContentValidator/ContentValidatorStrategy.php
  eZ/Publish/Core/Repository/Tests/ContentValidator/ContentValidatorStrategyTest.php
Labels: QA approved

#100 EZP-29886: Added loadObjectStateGroupByIdentifier/loadObjectStateByIdentifier methods to ObjectStateService
  eZ/Publish/API/Repository/ObjectStateService.php
  eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
  eZ/Publish/Core/Repository/ObjectStateService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ObjectStateServiceTest.php
  eZ/Publish/SPI/Repository/Decorator/ObjectStateServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ObjectStateServiceDecoratorTest.php
Labels: Feature, QA approved

#91 [EZP-31773] Remember me support multiple user providers
  eZ/Publish/Core/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php
Labels: QA approved

#101 EZP-31811: Fixed deleted relation fieldtypes
  eZ/Publish/Core/Repository/Helper/RelationProcessor.php
Labels: Bug, QA approved

#102 Fixed NotImplementedException exception message thrown by CompositeCriterion::getSpecifications
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/CompositeCriterion.php
Labels: Bug
