Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-07, with the labels that each got.

#70 EZP-31665: Serialize WrappedUser::apiUser as a reference.
  eZ/Publish/Core/MVC/Symfony/Security/Tests/UserWrappedTest.php
  eZ/Publish/Core/MVC/Symfony/Security/UserWrapped.php
Labels: Bug, QA approved

#81 EZP-31595: Parametrized embedded Content's URL generation
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
Labels: Bug, QA approved

#51 EZP-31588: As a Developer I want to configure search engine features with tags which follows same convention
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineFactory.php
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineIndexerFactory.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RegisterSearchEngineIndexerPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RegisterSearchEnginePass.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RegisterSearchEngineIndexerPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RegisterSearchEnginePassTest.php
  eZ/Publish/Core/Base/Container/Compiler/AbstractFieldTypeBasedPass.php
  eZ/Publish/Core/Base/Container/Compiler/Search/FieldRegistryPass.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
  eZ/Publish/Core/Base/Container/Compiler/TaggedServiceIdsIterator/BackwardCompatibleIterator.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/TaggedServiceIdsIterator/BackwardCompatibleIteratorTest.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/TaggedServiceIdsIterator/DeprecationErrorCollector.php
  eZ/Publish/Core/settings/search_engines/legacy.yml
Labels: DX, Fast-forward merge, Improvement

#88 [Tests] Bumped Solr Bundle version to test using the latest one
  bin/.travis/prepare_unittest.sh
Labels: Bug

#87 Allowed LogicalOr/LogicalNot/MatchAll/MatchNone criteria be used as part of the Trash query
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LogicalNot.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LogicalOr.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchAll.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchNone.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
  eZ/Publish/SPI/Repository/Values/Trash/Query/Criterion.php
Labels: Improvement, QA approved

#90 [Composer] Added conflict with Symfony Cache 5.0.11 and 5.1.3
  composer.json
Labels: Bug, Fast-forward merge
