Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-03, with the labels that each got.

#1 Replaced references to ezpublish-kernel with ezplatform-kernel
  Readme.md
  appveyor.yml
  bin/extract-translations.sh
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Bundle/EzPublishCoreBundle/behat_suites.yml
  eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/InstallerTagPass.php
  eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
  eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
  eZ/Publish/Core/Helper/FieldsGroups/RepositoryConfigFieldsGroupsListFactory.php
Labels: Improvement

#5 [Travis] Enabled notifications for Slack
  .travis.yml
Labels: Improvement

#6 [Travis] Named all jobs for better readability
  .travis.yml
Labels: Improvement

#3 EZP-31079: Provided validation for email uniqueness and login pattern
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
Labels: QA approved

#15 EZP-31518: Changed descriptions for welcome page
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
Labels: Improvement

#20 Removed @deprecated annotation from UserService::loadUserByLogin
  eZ/Publish/API/Repository/UserService.php
Labels: Bug

#12 EZP-30928: Dropped deprecated ContentService::removeTranslation method
  doc/bc/changes-1.0.md
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
  eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php
Labels: Improvement, QA approved

#9 EZP-31492: Used LanguageResolver instead of static languages list
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/Core/settings/repository/inner.yml
Labels: QA approved

#27 Replaced usages of deprecated expectExceptionMessageRegExp() with expectExceptionMessageMatches()
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConsoleCommandListenerTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterTest.php
Labels: Bug

#26 EZEE-3069: Ensured type of $destination property value is int for location based url aliases
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php
Labels: Bug, Ready for QA

#10 EZP-31517: Refactored Search Indexers to rely on Doctrine\DBAL
  eZ/Publish/Core/Search/Common/IncrementalIndexer.php
  eZ/Publish/Core/Search/Common/Indexer.php
  eZ/Publish/Core/Search/Legacy/Content/Indexer.php
  eZ/Publish/Core/settings/search_engines/legacy.yml
Labels: Improvement, QA approved

#23 EZP-31301: Refactored WordIndexer SearchIndex GW to rely on Doctrine
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Repository/SearchIndex.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
  eZ/Publish/Core/settings/search_engines/legacy.yml
  eZ/Publish/Core/settings/search_engines/legacy/indexer.yml
Labels: Improvement, QA approved

#16 EZP-31383: Implemented Role copying API
  eZ/Publish/API/Repository/Events/Role/BeforeCopyRoleEvent.php
  eZ/Publish/API/Repository/Events/Role/CopyRoleEvent.php
  eZ/Publish/API/Repository/RoleService.php
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/API/Repository/Values/User/Role.php
  eZ/Publish/API/Repository/Values/User/RoleCopyStruct.php
  eZ/Publish/Core/Event/RoleService.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/User/Handler.php
  eZ/Publish/Core/Persistence/Legacy/User/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
  eZ/Publish/Core/Repository/RoleService.php
  eZ/Publish/Core/Repository/Values/User/RoleCopyStruct.php
  eZ/Publish/SPI/Persistence/User/Handler.php
  eZ/Publish/SPI/Persistence/User/RoleCopyStruct.php
  eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php
Labels: Feature, QA approved

#22 EZP-31300: Refactored URL Search GW and handlers to rely on Doctrine
  doc/bc/changes-1.0.md
  eZ/Publish/API/Repository/Tests/URLServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriteriaConverterTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/CriterionHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalAndTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalNotTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalOrTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/MatchAllTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/MatchNoneTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/PatternTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/ValidityTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/VisibleOnlyTest.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriteriaConverter.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Base.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalAnd.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalNot.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalOr.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/MatchAll.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/MatchNone.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Pattern.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionId.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionIdentifier.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Validity.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/VisibleOnly.php
  eZ/Publish/Core/settings/storage_engines/legacy/url.yml
Labels: Improvement, QA approved

#14 EZP-31246: Refactored Test setup to stop relying on Database Handler
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/data/test_data.yaml
  eZ/Publish/Core/FieldType/Tests/Url/Gateway/DoctrineStorageTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/ConnectionHandlerTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/DeleteDoctrineQueryTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/DoctrineExpressionTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/InsertDoctrineQueryTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/SelectDoctrineQueryTest.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/TestCase.php
  eZ/Publish/Core/Persistence/Doctrine/Tests/UpdateDoctrineQueryTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/LanguageAwareTestCase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ObjectState/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Section/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/HandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Notification/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/LimitationConverterTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/test_data.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/AbstractTestCase.php
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/KeywordIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/RelationListIntegrationTest.php
  eZ/Publish/SPI/Tests/Persistence/BaseInMemoryCachedFileFixture.php
  eZ/Publish/SPI/Tests/Persistence/FileFixtureFactory.php
  eZ/Publish/SPI/Tests/Persistence/Fixture.php
  eZ/Publish/SPI/Tests/Persistence/FixtureImporter.php
  eZ/Publish/SPI/Tests/Persistence/PhpArrayFileFixture.php
  eZ/Publish/SPI/Tests/Persistence/YamlFixture.php
Labels: Improvement, Ready for review

#25 EZP-30392: [LSE] Dropped deprecated support for `%` as a wildcard
  doc/bc/changes-1.0.md
  eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler/Collection.php
Labels: Improvement, Ready for review
