Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-06, with the labels that each got.

#71 Updated Solr version to 7.7.3 in .travis.yml
  .travis.yml
Labels: Bug

#68 EZP-31663: Trigger location indexing after LocationService::createLocation
  eZ/Publish/Core/Search/Common/EventSubscriber/LocationEventSubscriber.php
  eZ/Publish/Core/Search/Tests/Common/LocationEventSubscriber/LocationEventSubscriberTest.php
Labels: Improvement

#75 [Composer] Set branch alias and dependencies for branch 1.0
  composer.json
Labels: Ready for review

#73 EZP-31344: Added getFieldGroup method
  eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
  eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
  eZ/Publish/Core/Helper/Tests/FieldsGroups/ArrayTranslatorFieldsGroupsListTest.php
Labels: QA approved

#77 EZP-31688: Removed obsolete forked 3rd party packages
  composer.json
Labels: Improvement, Ready for review

#78 EZEE-3191: Fixed wrong array key used in Version validation
  eZ/Publish/Core/Repository/Validator/VersionValidator.php
Labels: QA approved

#79 EZP-31698: Removed ConfigResolverCleanup cache warmer
  eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ConfigResolverCleanup.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Cache/Warmer/ConfigResolverCleanupTest.php
Labels: Bug, QA approved

#82 EZP-31701: Marked ezpublish.spi.search_engine as lazy
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
Labels: Bug, QA approved

#80 EZP-31650: Added Criterions handling for search in trash
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/DateMetadata.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LogicalAnd.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/SectionId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserMetadata.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Trash/ContentTypeName.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Trash/UserLogin.php
  eZ/Publish/Core/Base/Container/Compiler/Search/Legacy/CriteriaConverterPass.php
  eZ/Publish/Core/Base/Container/Compiler/Search/Legacy/SortClauseConverterPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Search/Legacy/CriteriaConverterPassTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/_fixtures/full_example_tree.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/DateMetadata.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Trash/ContentTypeName.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Trash/DateTrashed.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Trash/UserLogin.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_location.yml
  eZ/Publish/Core/settings/storage_engines/legacy/location.yml
  eZ/Publish/Core/settings/storage_engines/legacy/trash.yml
  eZ/Publish/SPI/Repository/Values/Trash/Query/Criterion.php
  eZ/Publish/SPI/Repository/Values/Trash/Query/SortClause.php
Labels: QA approved

#83 Fixed getting DB platform in Filtering Gateways to be lazy
  eZ/Publish/Core/Persistence/Legacy/Filter/Gateway/Content/Doctrine/DoctrineGateway.php
  eZ/Publish/Core/Persistence/Legacy/Filter/Gateway/Location/Doctrine/DoctrineGateway.php
Labels: Bug
