Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-10, with the labels that each got.

#116 EZEE-3287: Cast destinationId to int for content loading
  eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
Labels: QA approved

#115 EZP-31851: Added Twig helpers that abstracts content rendering
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/Event/ResolveRenderOptionsEvent.php
  eZ/Publish/Core/MVC/Symfony/Templating/Exception/InvalidResponseException.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderContentStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderLocationStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderEdgeSideInclude.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderInline.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderSubRequest.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderOptions.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderContentExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderLocationExtension.php
  eZ/Publish/SPI/MVC/Templating/BaseRenderStrategy.php
  eZ/Publish/SPI/MVC/Templating/RenderMethod.php
  eZ/Publish/SPI/MVC/Templating/RenderMethod/ControllerRenderMethod.php
  eZ/Publish/SPI/MVC/Templating/RenderStrategy.php
  eZ/Publish/SPI/Options/MutableOptionsBag.php
  eZ/Publish/SPI/Options/OptionsBag.php
Labels: Ready for review, Work in progress

#111 EZP-31773: Backported the fix for multiple user providers support
  eZ/Publish/Core/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php
Labels: Bug, QA approved, Ready for review

#118 EZP-31851: Added Unit tests for Render strategies
  eZ/Publish/Core/MVC/Symfony/Templating/RenderContentStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderLocationStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/BaseRenderStrategyTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderContentStrategyTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderLocationStrategyTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderOptionsTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderStrategyTest.php
Labels: Ready for review

#113 EZP-31741: Fixed features detection in eZ\Publish\Core\Repository\SearchService::supports
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Publish/Core/Search/Legacy/Content/Handler.php
  eZ/Publish/SPI/Search/VersatileHandler.php
Labels: Bug, QA approved

#125 Fixed timezone issues in SearchServiceAggregationTest
  eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
Labels: Bug

#122 Fixed RangeTest namespace
  eZ/Publish/API/Repository/Tests/Values/Content/Query/Aggregation/RangeTest.php
Labels: Bug

#123 EZP-32037: Replaced RenderMethods with Symfony built-in FragmentRenderers
  eZ/Bundle/EzPublishCoreBundle/Fragment/DirectFragmentRenderer.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Fragment/DirectFragmentRendererTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderContentStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderLocationStrategy.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderEdgeSideInclude.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderInline.php
  eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderSubRequest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/BaseRenderStrategyTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderContentStrategyTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderLocationStrategyTest.php
  eZ/Publish/SPI/MVC/Templating/BaseRenderStrategy.php
  eZ/Publish/SPI/MVC/Templating/RenderMethod.php
Labels: Ready for QA, Ready for review

#120 EZP-32045: Added support for AuthorTermAggregation
  eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
  eZ/Publish/Core/FieldType/Author/SearchField.php
Labels: Feature

#121 EZP-32045: Added support for SubtreeTermAggregation
  eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
  eZ/Publish/API/Repository/Tests/Values/Content/Query/Aggregation/Location/SubtreeTermAggregationTest.php
  eZ/Publish/API/Repository/Values/Content/Query/Aggregation/Location/SubtreeTermAggregation.php
Labels: Feature

#117 EZP-31825: Fixed user with user:password unable to change password
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Publish/API/Repository/Events/User/BeforeUpdateUserPasswordEvent.php
  eZ/Publish/API/Repository/Events/User/UpdateUserPasswordEvent.php
  eZ/Publish/API/Repository/Tests/UserServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Base/Exceptions/MissingUserFieldTypeException.php
  eZ/Publish/Core/Event/UserService.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/User/Handler.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/SPI/Persistence/User/Handler.php
  eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
Labels: Bug, QA approved, Ready for review
