Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-11, with the labels that each got.

#129 EZP-27458: Restructured Aggregation API integration tests
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/AbstractAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/ContentTypeGroupTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/ContentTypeTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/DataSetBuilder/TermAggregationDataSetBuilder.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/DateMetadataRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/AuthorTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/CheckboxTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/CountryTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/DateRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/DateTimeRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/FloatRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/FloatStatsAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/IntegerRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/IntegerStatsAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/KeywordTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/SelectionTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/TimeRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/FixtureGenerator/FieldAggregationFixtureGenerator.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/LanguageTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/ObjectStateTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/RawRangeAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/RawStatsAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/RawTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/SectionTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/SubtreeTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/UserMetadataTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/VisibilityTermAggregationTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
  phpunit-integration-legacy-solr.xml
Labels: Improvement

#130 EZP-32107: Added Score sort clause
  eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
  eZ/Publish/API/Repository/Tests/SearchService/SortClause/ScoreTest.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Score.php
Labels: DX, Feature, QA approved

#133 EZP-32151: Added Pagerfanta adapters for Repository Filtering API
  eZ/Publish/Core/Pagination/Pagerfanta/ContentFilteringAdapter.php
  eZ/Publish/Core/Pagination/Pagerfanta/LocationFilteringAdapter.php
  eZ/Publish/Core/Pagination/Tests/ContentFilteringAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/LocationFilteringAdapterTest.php
Labels: DX, Feature, QA approved

#132 EZP-32128: Thumbnails are no longer generated for removed image asset relation
  eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
Labels: QA approved

#136 EZEE-3356: Added JsonSerializableNormalizer for Serializer to handle Serializable interface
  eZ/Publish/Core/MVC/Symfony/Component/Serializer/SerializerTrait.php
Labels: Bug, QA approved
