Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-12, with the labels that each got.

#137 EZEE-3350: Added support to save additional data in ezImage FT
  composer.json
  eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/Core/FieldType/Image/Type.php
  eZ/Publish/Core/FieldType/Image/Value.php
  eZ/Publish/Core/FieldType/Tests/ImageTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
  eZ/Publish/Core/Persistence/Tests/Legacy/FieldValue/Converter/ImageConverterTest.php
  eZ/Publish/Core/Persistence/Tests/Legacy/FieldValue/Converter/_fixtures/ibexa_fav.png
  phpunit-integration-legacy-solr.xml
  phpunit-integration-legacy.xml
  phpunit.xml
Labels: QA approved, Ready for MERGE

#142 EZP-32031: Better BinaryBase filename generation
  eZ/Publish/Core/FieldType/BinaryBase/PathGenerator/LegacyPathGenerator.php
Labels: Improvement, QA approved

#135 EZP-32108: Added CustomField sort clause
  eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/CustomField.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Target/CustomFieldTarget.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/CustomFieldSortClauseParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/CustomFieldSortClauseParserTest.php
Labels: Feature

#138 EZP-32184: Added warning about possible memory leaks for reindex command
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Improvement, Ready for QA

#143 EZP-32111: Added ContentTranslatedName sort clause
  eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/SearchService/SortClause/AbstractSortClauseTest.php
  eZ/Publish/API/Repository/Tests/SearchService/SortClause/ContentTranslatedNameTest.php
  eZ/Publish/API/Repository/Tests/SearchService/SortClause/ScoreTest.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/ContentTranslatedName.php
Labels: Feature

#147 EZP-32220: Added new SettingService to manage application-wide settings
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Publish/API/Repository/Events/Setting/BeforeCreateSettingEvent.php
  eZ/Publish/API/Repository/Events/Setting/BeforeDeleteSettingEvent.php
  eZ/Publish/API/Repository/Events/Setting/BeforeUpdateSettingEvent.php
  eZ/Publish/API/Repository/Events/Setting/CreateSettingEvent.php
  eZ/Publish/API/Repository/Events/Setting/DeleteSettingEvent.php
  eZ/Publish/API/Repository/Events/Setting/UpdateSettingEvent.php
  eZ/Publish/API/Repository/SettingService.php
  eZ/Publish/API/Repository/Tests/SettingServiceTest.php
  eZ/Publish/API/Repository/Values/Setting/Setting.php
  eZ/Publish/API/Repository/Values/Setting/SettingCreateStruct.php
  eZ/Publish/API/Repository/Values/Setting/SettingUpdateStruct.php
  eZ/Publish/Core/Event/SettingService.php
  eZ/Publish/Core/Event/Tests/SettingServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Handler.php
  eZ/Publish/Core/Persistence/Cache/SettingHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/SettingHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Setting/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Setting/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Setting/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Setting/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Setting/SettingHandlerTest.php
  eZ/Publish/Core/Repository/SettingService.php
  eZ/Publish/Core/Repository/SiteAccessAware/SettingService.php
  eZ/Publish/Core/settings/policies.yml
  eZ/Publish/Core/settings/repository/autowire.yml
  eZ/Publish/Core/settings/repository/event.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/repository/siteaccessaware.yml
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/setting.yml
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/SPI/Persistence/Handler.php
  eZ/Publish/SPI/Persistence/Setting/Handler.php
  eZ/Publish/SPI/Persistence/Setting/Setting.php
  eZ/Publish/SPI/Repository/Decorator/SettingServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SettingServiceDecoratorTest.php
  eZ/Publish/SPI/Tests/Persistence/FixtureImporter.php
  phpunit-integration-legacy.xml
Labels: Ready for review

#146 EZP-32219: Fix ContentType sorting defaults has no effect on new created objects
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Repository/ContentService.php
Labels: Bug, QA approved

#148 EZP-32214: Made purge type configuration using env vars resolvable at compile time
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
Labels: Improvement, Ready for review

#149 EZP-32247: As a Developer I want load user group by remote id
  eZ/Publish/API/Repository/Tests/UserServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
Labels: DX, Feature, Ready for QA

#150 EZP-32250: Exposed PasswordHashService APIs
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/PlatformInstallerBundle/src/Command/ValidatePasswordHashesCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
  eZ/Publish/API/Repository/PasswordHashService.php
  eZ/Publish/API/Repository/Values/User/User.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserStorageGatewayTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/FieldType/User/UserStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
  eZ/Publish/Core/Repository/Tests/User/PasswordHashServiceTest.php
  eZ/Publish/Core/Repository/User/PasswordHashService.php
  eZ/Publish/Core/Repository/User/PasswordHashServiceInterface.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
Labels: DX, Improvement, Ready for QA

#144 EZP-32110: Exposed more search result data from Pagefanta adapters
  eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
  eZ/Publish/Core/MVC/Symfony/Controller/Content/QueryController.php
  eZ/Publish/Core/MVC/Symfony/Controller/QueryRenderController.php
  eZ/Publish/Core/MVC/Symfony/Controller/Tests/QueryRenderControllerTest.php
  eZ/Publish/Core/Pagination/Pagerfanta/AbstractSearchResultAdapter.php
  eZ/Publish/Core/Pagination/Pagerfanta/AdapterFactory/SearchHitAdapterFactory.php
  eZ/Publish/Core/Pagination/Pagerfanta/ContentSearchHitAdapter.php
  eZ/Publish/Core/Pagination/Pagerfanta/FixedSearchResultHitAdapter.php
  eZ/Publish/Core/Pagination/Pagerfanta/LocationSearchHitAdapter.php
  eZ/Publish/Core/Pagination/Pagerfanta/Pagerfanta.php
  eZ/Publish/Core/Pagination/Pagerfanta/SearchResultAdapter.php
  eZ/Publish/Core/Pagination/Tests/AdapterFactory/SearchHitAdapterFactoryTest.php
  eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/FixedSearchResultHitAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/LocationSearchAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/LocationSearchHitAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/PagerfantaTest.php
Labels: DX, Feature, Ready for QA

#155 EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release
  COPYRIGHT
  LICENSE
  LICENSE-bul
  Readme.md
Labels: Feature, Ready for review
