Repository ezsystems/ezplatform-kernel, pull requests merged in 2020-09, with the labels that each got.

#103 EZP-31817: Enabled ezfloat values indexing
  eZ/Publish/API/Repository/Tests/FieldType/FloatIntegrationTest.php
  eZ/Publish/Core/FieldType/Float/Type.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/FloatConverter.php
Labels: QA approved

#112 [DX] Improved GitHub Pull Request template checklist
  .github/pull_request_template.md
Labels: DX, Ready for review

#108 EZP-31740: Introduced SiteAccess-aware NFS adapter
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/Config/ComplexConfigProcessor.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/ConfigurationFactory/Flysystem.php
  eZ/Bundle/EzPublishIOBundle/Flysystem/Adapter/SiteAccessAwareLocalAdapter.php
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Bundle/EzPublishIOBundle/Tests/Flysystem/Adapter/SiteAccessAwareLocalAdapterTest.php
  eZ/Publish/SPI/SiteAccess/ConfigProcessor.php
Labels: Bug, QA approved

#99 EZP-31462: Added command checking if there are any unsupported password hash types
  eZ/Bundle/PlatformInstallerBundle/src/Command/ValidatePasswordHashesCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
  eZ/Publish/API/Repository/Exceptions/PasswordInUnsupportedFormatException.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/Values/User/User.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserDoctrineStorageGatewayTest.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserStorageGatewayTest.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/_fixtures/unsupported_hash.yaml
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/FieldType/User/UserStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php
  eZ/Publish/Core/Repository/User/Exception/UnsupportedPasswordHashType.php
  eZ/Publish/Core/Repository/User/PasswordHashService.php
Labels: Improvement, QA approved

#110 EZP-31912: Fixed decorating binary files URLs with proper absolute prefix
  eZ/Bundle/EzPublishIOBundle/Tests/DependencyInjection/EzPublishIOExtensionTest.php
  eZ/Bundle/EzPublishIOBundle/Tests/_fixtures/url_prefix_test_config.yaml
  eZ/Publish/Core/IO/Tests/UrlDecorator/AbsolutePrefixTest.php
  eZ/Publish/Core/IO/UrlDecorator/AbsolutePrefix.php
Labels: Bug, QA approved
