Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-11, with the labels that each got.

#249 IBX-843: Introduced ContentLocationMapper
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Publish/Core/Repository/Mapper/ContentLocationMapper/ContentLocationMapper.php
  eZ/Publish/Core/Repository/Mapper/ContentLocationMapper/DecoratedLocationService.php
  eZ/Publish/Core/Repository/Mapper/ContentLocationMapper/InMemoryContentLocationMapper.php
  eZ/Publish/Core/Repository/Mapper/Readme.md
  eZ/Publish/Core/Repository/Tests/Mapper/ContentLocationMapper/DecoratedLocationServiceTest.php
  eZ/Publish/Core/Repository/Tests/Mapper/ContentLocationMapper/InMemoryContentLocationMapperTest.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/content_location_mapper.yml
Labels: Feature

#254 Fixed invalid PHPDoc for `Criterion::$value`
  eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
Labels: Ready for review

#250 IBX-1308: Added is_system flag to the ContentTypeGroup
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/data/test_data.yaml
  eZ/Publish/API/Repository/Tests/_fixtures/generate-fixtures.php
  eZ/Publish/API/Repository/Values/ContentType/ContentTypeGroup.php
  eZ/Publish/API/Repository/Values/ContentType/ContentTypeGroupStruct.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/_fixtures/existing_groups.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/_fixtures/map_load_group.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Mapper/ContentTypeDomainMapper.php
  eZ/Publish/SPI/Persistence/Content/Type/Group.php
  eZ/Publish/SPI/Persistence/Content/Type/Group/CreateStruct.php
  eZ/Publish/SPI/Persistence/Content/Type/Group/UpdateStruct.php
  src/bundle/Core/Command/SetSystemContentTypeGroupCommand.php
Labels: Feature, QA approved, Ready for review

#262 IBX-1517: Made quotes in exception for Ancestor criterion consistent
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/Ancestor.php
Labels: Bug, Ready for review

#261 IBX-1518: Provided separate messages for Subtree Limitation validation
  eZ/Publish/Core/Limitation/SubtreeLimitationType.php
Labels: Ready for review

#265 Provided PHP8 compatibility for moving content
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: Bug, Ready for QA

#267 IBX-1564: Fixed undefined policies loading order
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
Labels: Bug
