Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-09, with the labels that each got.

#230 Removed return statement from RepositoryAuthenticationProvider::checkAuthentication
  eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
Labels: Ready for review

#232 [Tests] Fixed Repository BatchIteratorAdapter tests
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentFilteringAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationFilteringAdapterTest.php
  phpunit.xml
Labels: Bug, Ready for review

#195 Added support for all Belgium national languages 🇧🇪
  eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
Labels: Feature

#233 Changed generator name to Ibexa DXP
  eZ/Bundle/EzPublishCoreBundle/Resources/views/pagelayout.html.twig
Labels: Improvement
