Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-05, with the labels that each got.

#181 IBX-300: Added timezone offset to timestamp
  eZ/Publish/API/Repository/Tests/FieldType/DateIntegrationTest.php
  eZ/Publish/Core/FieldType/Date/Value.php
  eZ/Publish/Core/FieldType/Tests/DateTest.php
Labels: Bug, QA approved

#180 IBX-340: Allowed URL Gateway queries to not perform count operations
  eZ/Publish/API/Repository/Tests/BaseURLServiceTest.php
  eZ/Publish/API/Repository/Tests/URLServiceTest.php
  eZ/Publish/API/Repository/Values/URL/SearchResult.php
  eZ/Publish/API/Repository/Values/URL/URLQuery.php
  eZ/Publish/Core/FieldType/Tests/Url/Gateway/DoctrineStorageTest.php
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Gateway/_fixtures/urls.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/HandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/URL/Handler.php
Labels: QA approved

#185 IBX-300 changed search field data to using timezone for timestamp
  eZ/Publish/Core/FieldType/Date/SearchField.php
Labels: Bug, QA approved

#187 removed timezone for ezdate field from tests
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/DateRangeAggregationTest.php
Labels: Bug, Ready for review
