Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-12, with the labels that each got.

#264 IBX-1489: Provided integration test for Installers for PHP8
  .github/workflows/ci.yaml
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Imagine/AliasGenerator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/VariationPurger/LegacyStorageImageFileList.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderProvider/GenericProviderTest.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CoreInstaller.php
  eZ/Publish/API/Repository/Iterator/BatchIterator.php
  eZ/Publish/API/Repository/Tests/LegacySchemaImporter.php
  eZ/Publish/API/Repository/Values/UserPreference/UserPreferenceList.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
  eZ/Publish/Core/FieldType/Author/AuthorCollection.php
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/FieldSettings.php
  eZ/Publish/Core/FieldType/Media/Type.php
  eZ/Publish/Core/FieldType/Tests/AuthorTest.php
  eZ/Publish/Core/FieldType/Tests/BinaryFileTest.php
  eZ/Publish/Core/FieldType/Tests/CheckboxTest.php
  eZ/Publish/Core/FieldType/Tests/CountryTest.php
  eZ/Publish/Core/FieldType/Tests/DateAndTimeTest.php
  eZ/Publish/Core/FieldType/Tests/DateTest.php
  eZ/Publish/Core/FieldType/Tests/EmailAddressTest.php
  eZ/Publish/Core/FieldType/Tests/FloatTest.php
  eZ/Publish/Core/FieldType/Tests/ISBNTest.php
  eZ/Publish/Core/FieldType/Tests/ImageAssetTest.php
  eZ/Publish/Core/FieldType/Tests/ImageTest.php
  eZ/Publish/Core/FieldType/Tests/IntegerTest.php
  eZ/Publish/Core/FieldType/Tests/KeywordTest.php
  eZ/Publish/Core/FieldType/Tests/MapLocationTest.php
  eZ/Publish/Core/FieldType/Tests/MediaTest.php
  eZ/Publish/Core/FieldType/Tests/RelationListTest.php
  eZ/Publish/Core/FieldType/Tests/RelationTest.php
  eZ/Publish/Core/FieldType/Tests/SelectionTest.php
  eZ/Publish/Core/FieldType/Tests/TextBlockTest.php
  eZ/Publish/Core/FieldType/Tests/TextLineTest.php
  eZ/Publish/Core/FieldType/Tests/TimeTest.php
  eZ/Publish/Core/FieldType/Tests/UrlTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/TextBlock/SearchField.php
  eZ/Publish/Core/IO/IOMetadataHandler/LegacyDFSCluster.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/User/ParameterProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/UrlAlias.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/URI.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Regex.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Tests/Legacy/FieldValue/Converter/ImageConverterTest.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
  eZ/Publish/SPI/FieldType/Generic/Tests/GenericTest.php
  eZ/Publish/SPI/FieldType/Tests/FieldTypeTest.php
  eZ/Publish/SPI/Persistence/Content/Location/Trash/TrashResult.php
  tests/integration/Installer/Installer/CoreInstallerTest.php
  tests/integration/Installer/TestCase.php
  tests/integration/Installer/TestKernel.php
Labels: Bug, QA approved

#268 Added PHPStan analysis
  .github/workflows/ci.yaml
  .gitignore
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
  eZ/Bundle/EzPublishIOBundle/Command/MigrateFilesCommand.php
  eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileIterator/LegacyStorageFileIterator.php
  eZ/Publish/Core/FieldType/Media/Type.php
  eZ/Publish/SPI/Persistence/Filter/Content/LazyContentItemListIterator.php
  eZ/Publish/SPI/Persistence/Filter/LazyListIterator.php
  eZ/Publish/SPI/Persistence/Filter/Location/LazyLocationListIterator.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: Improvement, Ready for review

#269 IBX-1310: Created subscriber methods for assigning/unassigning user to groups
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/Search/Common/EventSubscriber/UserEventSubscriber.php
Labels: Bug, QA approved, Ready for MERGE

#271 Moved php-cs-fixer to another job
  .github/workflows/ci.yaml
Labels: Improvement, Ready for review

#274 IBX-1489: Changed ProxyManager dependency
  composer.json
Labels: Bug, Ready for review

#273 IBX-1549: changed validation content to only one language
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Validator/VersionValidator.php
Labels: Bug, QA approved, Ready for MERGE
