Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-08, with the labels that each got.

#212 IBX-764: Added Kernel / Repository Test API
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/doctrine.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/ezpublish.yaml
  eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/framework.yaml
  eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/security.yaml
  eZ/Bundle/EzPublishCoreBundle/Tests/Resources/services/fixture-services.yaml
  phpunit-integration-legacy.xml
  src/contracts/Test/IbexaKernelTestCase.php
  src/contracts/Test/IbexaTestKernel.php
  tests/integration/BasicKernelTest.php
Labels: Feature, Ready for review

#222 IBX-850: [Tests] Fixed PSR-incompatible test namespaces
  tests/bundle/Core/EventListener/BackwardCompatibleCommandListenerTest.php
  tests/integration/Core/FieldType/User/UserStorage/Gateway/UserDoctrineStorageGatewayTest.php
  tests/lib/Persistence/Legacy/Filter/CriterionQueryBuilder/Content/Type/ContentTypeGroupIdQueryBuilderTest.php
  tests/lib/Persistence/Legacy/Filter/CriterionQueryBuilder/Content/Type/ContentTypeQueryBuildersTest.php
Labels: Bug, Ready for MERGE

#223 [Tests] Dropped unused searchable Field Type overrides for Solr
  eZ/Publish/API/Repository/Tests/FieldType/SearchableFloat.php
  eZ/Publish/API/Repository/Tests/FieldType/SearchableImage.php
  eZ/Publish/API/Repository/Tests/FieldType/SearchableMedia.php
  eZ/Publish/API/Repository/Tests/FieldType/SearchableUrl.php
Labels: Bug

#224 IBX-883: [Tests] Dropped PHPUnit5CompatTrait
  eZ/Publish/Core/Base/Tests/PHPUnit5CompatTrait.php
Labels: Improvement, Ready for review, DX

#218 IBX-810: Extendable repository configuration
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  src/bundle/Core/.gitkeep
  src/bundle/Core/DependencyInjection/Configuration/Parser/Repository/FieldGroups.php
  src/bundle/Core/DependencyInjection/Configuration/Parser/Repository/Options.php
  src/bundle/Core/DependencyInjection/Configuration/Parser/Repository/Search.php
  src/bundle/Core/DependencyInjection/Configuration/Parser/Repository/Storage.php
  src/bundle/Core/DependencyInjection/Configuration/RepositoryConfigParser.php
  src/bundle/Core/DependencyInjection/Configuration/RepositoryConfigParserInterface.php
  tests/bundle/Core/.gitkeep
  tests/bundle/Core/DependencyInjection/Configuration/RepositoryConfigParserTest.php
Labels: Feature, QA approved

#228 [Composer] Added conflict with symfony/dependency-injection v3.5.7
  composer.json
Labels: Ready for review
