Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-07, with the labels that each got.

#208 IBX-688: SettingService::buildSettingDomainObject deserialize hashes as stdClass
  eZ/Publish/API/Repository/Tests/SettingServiceTest.php
  eZ/Publish/Core/Repository/SettingService.php
Labels: Bug

#209 Documented \eZ\Publish\API\Repository\SettingService exceptions
  eZ/Publish/API/Repository/SettingService.php
  eZ/Publish/Core/Repository/SettingService.php
Labels: DX

#210 Added \eZ\Publish\API\Repository\Values\Filter\Filter::{withOffset,withLimit} methods
  eZ/Publish/API/Repository/Tests/Values/Filter/FilterTest.php
  eZ/Publish/API/Repository/Values/Filter/Filter.php
Labels: DX, Improvement

#206 IBX-665: Bumped Symfony dependency to 5.3
  composer.json
  eZ/Bundle/EzPublishCoreBundle/EventListener/SessionInitByPostListener.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/SessionSetDynamicNameListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/session.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SessionInitByPostListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SessionSetDynamicNameListenerTest.php
Labels: Improvement, Ready for review

#211 IBX-719: Introduced BatchIterator
  eZ/Publish/API/Repository/Iterator/BatchIterator.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/AbstractSearchAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentFilteringAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentInfoSearchAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentSearchAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/LocationFilteringAdapter.php
  eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/LocationSearchAdapter.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/AbstractSearchAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentFilteringAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentInfoSearchAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentSearchAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationFilteringAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationSearchAdapterTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorTest.php
  eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorTestAdapter.php
  eZ/Publish/API/Repository/Values/Content/Search/SearchResult.php
Labels: DX, Doc needed, Feature

#205 IBX-605: Refactored and optimized orphaned URLs deleting
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
Labels: Improvement, QA approved

#217 [FAST FORWARD MERGE] Merge up for ezpublish-kernel 7.5 -> ezplatform-kernel 1.3
  .php_cs
  composer.json
  src/bundle/Core/.gitkeep
  src/bundle/Debug/.gitkeep
  src/bundle/IO/.gitkeep
  src/bundle/Installer/.gitkeep
  src/bundle/LegacySearchEngine/.gitkeep
  src/contracts/.gitkeep
  src/lib/.gitkeep
  tests/bundle/Core/.gitkeep
  tests/bundle/Debug/.gitkeep
  tests/bundle/IO/.gitkeep
  tests/bundle/Installer/.gitkeep
  tests/bundle/LegacySearchEngine/.gitkeep
  tests/integration/Core/.gitkeep
  tests/integration/Debug/.gitkeep
  tests/integration/IO/.gitkeep
  tests/integration/Installer/.gitkeep
  tests/integration/LegacySearchEngine/.gitkeep
  tests/lib/.gitkeep
Labels: Fast-forward merge

#213 IBX-175: Fixed invalid VersionValidator errors output when validation fails for multilingual content
  eZ/Publish/API/Repository/Tests/ContentService/VersionValidatorTest.php
  eZ/Publish/Core/Repository/Validator/VersionValidator.php
Labels: Bug, QA approved

#215 IBX-704: Added LocationChildrenTermAggregation
  eZ/Publish/API/Repository/Tests/SearchService/Aggregation/LocationChildrenTermAggregationTest.php
  eZ/Publish/API/Repository/Values/Content/Query/Aggregation/Location/LocationChildrenTermAggregation.php
Labels: Doc needed, Improvement, QA approved

#219 [FAST FORWARD] Merged up changes from ezpublish-kernel repository
  .github/workflows/ci.yaml
  .travis.yml
  composer.json
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSizeExtensionTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FileSizeExtension.php
  phpunit-integration-legacy.xml
Labels: Bug, Fast-forward merge, Feature, Improvement
