Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-01, with the labels that each got.

#158 EZP-31795: Added VersionInfo to getThumbnail method in order to utilise builtin caching mechanism
  eZ/Publish/Core/FieldType/Image/ImageThumbnailStrategy.php
  eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
  eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
  eZ/Publish/Core/Repository/Strategy/ContentThumbnail/Field/ContentFieldStrategy.php
  eZ/Publish/Core/Repository/Strategy/ContentThumbnail/FirstMatchingFieldStrategy.php
  eZ/Publish/Core/Repository/Strategy/ContentThumbnail/StaticStrategy.php
  eZ/Publish/Core/Repository/Strategy/ContentThumbnail/ThumbnailChainStrategy.php
  eZ/Publish/Core/Repository/Tests/ContentThumbnail/ContentFieldStrategyTest.php
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/Core/settings/thumbnails.yml
  eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/Field/ThumbnailStrategy.php
  eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/ThumbnailStrategy.php
Labels: QA approved

#159 EZP-32284: Made `type` parameter optional in InstallPlatformCommand
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Labels: Improvement, Ready for review

#157 EZP-31795: Introduced proxy objects for content thumbnails
  eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ProxyCacheWarmer.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/thumbnails.yml
  eZ/Publish/Core/FieldType/Image/ImageThumbnailProxyStrategy.php
  eZ/Publish/Core/settings/thumbnails.yml
Labels: QA approved

#161 EZP-32281: IndexRequestListener requires redirect
  eZ/Bundle/EzPublishCoreBundle/EventListener/IndexRequestListener.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/IndexRequestListenerTest.php
Labels: Bug, QA approved
