Repository ezsystems/ezplatform-kernel, pull requests merged in 2021-04, with the labels that each got.

#175 Added missing @property-read annotations to Thumbnail class
  eZ/Publish/API/Repository/Values/Content/Thumbnail.php
Labels: DX, Improvement

#178 IBX-143: Fixed merge-up of reindex command changes
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: Bug, Ready for review

#173 [Travis] Switched to Flex setup for Behat tests
  .travis.yml
  bin/.travis/prepare_behat.sh
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/YamlConfigurationContext.php
Labels: Ready for review

#179 IBX-85: Fixed Content cache containing invalid "uri" for file field types
  .github/workflows/release.yml
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
  eZ/Publish/Core/FieldType/BinaryBase/Type.php
  eZ/Publish/Core/FieldType/BinaryFile/Type.php
  eZ/Publish/Core/FieldType/Media/Type.php
  eZ/Publish/Core/FieldType/Tests/BinaryFileTest.php
  eZ/Publish/Core/MVC/Symfony/FieldType/BinaryBase/ContentDownloadUrlGenerator.php
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/SPI/FieldType/BinaryBase/PathGenerator.php
  eZ/Publish/SPI/FieldType/BinaryBase/PathGeneratorInterface.php
  eZ/Publish/SPI/FieldType/BinaryBase/RouteAwarePathGenerator.php
Labels: QA approved
