Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-11, with the labels that each got.

#349 Added `IbexaTestKernel::addSyntheticService` to reduce duplication
  src/contracts/Test/IbexaTestKernel.php
Labels: Improvement

#348 Introduced `IbexaKernelTestTrait` to reduce code duplication
  src/contracts/Test/IbexaKernelTestCase.php
  src/contracts/Test/IbexaKernelTestTrait.php
Labels: Improvement

#351 IBX-4384: Handled sort clauses in `loadLocationChildren`
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/Core/Repository/LocationService.php
Labels: Bug, QA approved, Ready for MERGE

#346 [Keyword fieldtype] Added ORDER BY to keyword query
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/DoctrineStorage.php
Labels: Improvement, QA approved, Ready for review

#353 Separated `security` settings for IbexaTestKernel
  src/contracts/Test/IbexaTestKernel.php
Labels: Improvement, Ready for review
