Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-10, with the labels that each got.

#336 IBX-3856: Changed Checkbox's value to never be considered empty
  eZ/Publish/API/Repository/Tests/FieldType/CheckboxIntegrationTest.php
  eZ/Publish/Core/FieldType/Checkbox/Type.php
  eZ/Publish/Core/FieldType/FieldType.php
  eZ/Publish/Core/FieldType/Tests/CheckboxTest.php
Labels: QA approved, Ready for review, Doc needed

#342 IBX-3595: Fixed processing timestamps in ibexa:timestamps:to-utc command
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
Labels: Bug, QA approved, Ready for MERGE

#341 IBX-4008: Fixed incorrect total count of LocationService::find items
  eZ/Publish/API/Repository/Tests/Filtering/BaseRepositoryFilteringTestCase.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/ContentList.php
  eZ/Publish/API/Repository/Values/Content/LocationList.php
  eZ/Publish/Core/Pagination/Pagerfanta/LocationFilteringAdapter.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/SPI/Persistence/Filter/Location/Handler.php
  src/contracts/Repository/Collections/TotalCountAwareInterface.php
Labels: Bug, QA approved

#343 IBX-4001: Made `ezimagefile` entries unique based on `fieldId` and `path`
  eZ/Publish/Core/FieldType/Image/ImageStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
  tests/integration/Core/Image/ImageStorage/ImageStorageTest.php
  tests/integration/Core/Image/ImageStorage/image.jpg
Labels: Bug, QA approved, Ready for MERGE

#344 IBX-4018: Implement `supportsDenormalization` method for `CompoundMatcherNormalizer`
  eZ/Publish/Core/MVC/Symfony/Component/Serializer/CompoundMatcherNormalizer.php
  eZ/Publish/Core/MVC/Symfony/Component/Tests/Serializer/CompoundMatcherNormalizerTest.php
Labels: Improvement, QA approved, Ready for MERGE
