Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-02, with the labels that each got.

#284 Exposed `getSchemaFiles` & `getFixtures` methods in IbexaTestKernel
  src/contracts/Test/IbexaKernelTestCase.php
  src/contracts/Test/IbexaTestKernel.php
Labels: Improvement, Ready for review

#285 IBX-1090: Fixed calculations and displaying of ezdate FT, as it should always be represented in UTC
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Publish/API/Repository/Tests/FieldType/DateIntegrationTest.php
  eZ/Publish/Core/FieldType/Date/SearchField.php
  eZ/Publish/Core/FieldType/Date/Value.php
  eZ/Publish/Core/FieldType/Tests/DateTest.php
Labels: QA approved

#287 IBX-2295: Fixed SiteAccess-aware ConfigScopeChangeSubscriber
  eZ/Bundle/EzPublishCoreBundle/EventListener/ConfigScopeListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Publish/Core/IO/Adapter/LocalAdapter.php
  eZ/Publish/Core/IO/ConfigScopeChangeAwareIOService.php
  eZ/Publish/Core/IO/Tests/ConfigScopeChangeAwareIOServiceTest.php
  eZ/Publish/SPI/MVC/EventSubscriber/ConfigScopeChangeSubscriber.php
Labels: Bug, QA approved, Doc needed
