Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-01, with the labels that each got.

#277 IBX-1182: Fixed merge
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
Labels: Bug, Ready for MERGE

#281 Fixed `Language::$id` phpdoc being not accurate
  eZ/Publish/SPI/Persistence/Content/Language.php
Labels: Ready for review

#276 [CI] Moved Behat tests to Github Actions
  .github/workflows/browser-tests.yaml
  .travis.yml
Labels: Ready for review

#282 IBX-1999: Added countAll function for URLWildcards
  eZ/Publish/API/Repository/Tests/URLWildcardServiceTest.php
  eZ/Publish/API/Repository/URLWildcardService.php
  eZ/Publish/Core/Persistence/Cache/UrlWildcardHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Handler.php
  eZ/Publish/Core/Repository/URLWildcardService.php
  eZ/Publish/SPI/Persistence/Content/UrlWildcard/Handler.php
  eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php
Labels: Improvement, QA approved
