Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-05, with the labels that each got.

#304 IBX-1669: merge up to 1.3
  eZ/Publish/API/Repository/Tests/FieldType/RelationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/RelationListIntegrationTest.php
  eZ/Publish/Core/FieldType/Relation/Type.php
  eZ/Publish/Core/FieldType/RelationList/Type.php
  eZ/Publish/Core/FieldType/Tests/EmailAddressValidatorTest.php
  eZ/Publish/Core/FieldType/Tests/RelationListTest.php
  eZ/Publish/Core/FieldType/Tests/RelationTest.php
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/SPI/Tests/FieldType/RelationIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/RelationListIntegrationTest.php
  src/lib/Repository/Validator/TargetContentValidator.php
  src/lib/Repository/Validator/TargetContentValidatorInterface.php
  tests/lib/Repository/Validator/TargetContentValidatorTest.php
Labels: Ready for MERGE

#308 IBX-2844: Handled historic URL aliases cache invalidation
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
Labels: Bug, QA approved, Ready for MERGE

#188 IBX-392: Fixed overriding view parameters for view_embed only permission
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
Labels: Bug, QA approved, Ready for review

#305 IBX-2825: Implemented `Location` target
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/LanguageLimitationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
  eZ/Publish/Core/Limitation/LanguageLimitationType.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
  src/contracts/Limitation/Target/DestinationLocation.php
Labels: Bug, QA approved, Ready for MERGE

#309 IBX-2880: Added PasswordExpiredException
  eZ/Publish/Core/MVC/Symfony/Security/Tests/UserCheckerTest.php
  eZ/Publish/Core/MVC/Symfony/Security/UserChecker.php
  src/lib/MVC/Symfony/Security/Exception/PasswordExpiredException.php
Labels: Bug, QA approved, Ready for MERGE

#312 Fixed dir name for url wildcard
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/UrlWildcardHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/url_wildcard.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_wildcard_criterion_handlers.yml
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriteriaConverter.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/DestinationUrl.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/LogicalAnd.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/LogicalNot.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/LogicalOr.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/MatchAll.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/MatchNone.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/SourceUrl.php
  src/lib/Persistence/Legacy/Content/UrlWildcard/Query/CriterionHandler/Type.php
Labels: QA approved, Ready for MERGE
