Repository ezsystems/ezplatform-kernel, pull requests merged in 2022-08, with the labels that each got.

#325 IBX-360 - Added \d+ requirement on contentId parameter for ez_content_download_field_id route
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
Labels: Bug, QA approved

#326 IBX-3167: Fixed performance issue in URL Alias cache invalidation
  eZ/Publish/API/Repository/Values/Content/ContentInfo.php
  eZ/Publish/API/Repository/Values/Content/Field.php
  eZ/Publish/API/Repository/Values/Content/Language.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php
  eZ/Publish/Core/Repository/Values/Content/Content.php
  eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php
Labels: Improvement, QA approved

#324 IBX-3451: [Behat] Removed depending on APP_ENV when loading Context services
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
Labels: QA approved, Ready for MERGE

#328 IBX-3557: Provided Location target for `updateLocation` API method
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
  eZ/Publish/Core/Repository/LocationService.php
Labels: Bug, QA approved

#329 IBX-3588: Enhanced `ContentFieldValidation` exception
  eZ/Publish/Core/Base/Exceptions/ContentFieldValidationException.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/UserService.php
Labels: Improvement, QA approved

#322 IBX-3334: Skipped migrating binary file or its metadata when using the same handler
  eZ/Bundle/EzPublishIOBundle/Migration/FileMigrator/FileMigrator.php
  tests/bundle/IO/Migration/FileMigratorTest.php
Labels: Bug, QA approved, Ready for MERGE

#332 IBX-3606: Removed duplicate siteaccess names
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Provider/StaticSiteAccessProvider.php
Labels: Bug, QA approved, Ready for review

#331 Optimized API Content::getField method
  eZ/Publish/Core/Repository/Values/Content/Content.php
  tests/lib/Repository/Values/Content/ContentTest.php
Labels: Improvement
