Repository ezsystems/ezplatform-kernel, pull requests merged in 2023-02, with the labels that each got.

#359 IBX-4877: Allow Location-based Content preview
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/pagelayout.html.twig
  eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
  eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php
  phpstan-baseline.neon
Labels: Improvement, QA approved, Ready for MERGE

#356 IBX-4461: Fixed handling trailing slash for isUriPrefixExcluded
  eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
Labels: Bug, QA approved, Ready for MERGE

#362 [Composer] Disallowed every not specified Composer plugin
  composer.json
Labels: Bug, Improvement

#360 IBX-4477: Added LocationService::getSubtreeSize method
  eZ/Publish/API/Repository/LocationService.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/API/Repository/Values/ContentType/ContentType.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
  eZ/Publish/SPI/Repository/Decorator/LocationServiceDecorator.php
Labels: Bug, QA approved

#361 IBX-4647: Added WebpFormatVariationPathGenerator handling .webp images
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  src/bundle/Core/Imagine/VariationPathGenerator/WebpFormatVariationPathGenerator.php
  tests/bundle/Core/Imagine/VariationPathGenerator/WebpFormatVariationPathGeneratorTest.php
Labels: Bug, QA approved, Ready for MERGE, Ready for review
