Repository ezsystems/ezplatform-kernel, pull requests merged in 2023-07, with the labels that each got.

#378 IBX-5388: Added index on `contentclassattribute_id` in the `ezcontentobject_link` table
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
Labels: Improvement, QA approved, Doc needed

#379 IBX-6185: Add more PHP file types to default upload blocklist (#3153)
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
Labels: QA approved, Ready for review

#375 IBX-6017: Implemented `loadVersionInfoListByContentInfo` PAPI method
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/Core/Helper/TranslationHelper.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
  eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php
  src/contracts/Test/IbexaTestKernel.php
  tests/integration/Core/Repository/ContentService/LoadVersionInfoTest.php
  tests/integration/Core/RepositoryTestCase.php
Labels: Feature, QA approved
