Repository ezsystems/ezplatform-kernel, pull requests merged in 2023-01, with the labels that each got.

#355 IBX-4326: Custom URL aliases reparenting
  eZ/Bundle/EzPublishCoreBundle/Features/Context/ExceptionContext.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
Labels: Bug, QA approved, Ready for MERGE

#357 IBX-4700: Added `versionNo` argument for Content Proxy
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapper.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperInterface.php
Labels: Improvement, QA approved, Ready for MERGE

#358 IBX-4857: Changed help output for ibexa:reindex command
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Improvement, Ready for review
