Repository ezsystems/ezplatform-kernel, pull requests merged in 2023-08, with the labels that each got.

#382 EZP-29574: Moved testLoadUserByTokenThrowsNotFoundException after tests depending of testLoadUserByToken
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
Labels: Bug, Ready for review

#176 IBX-152: Optimized LSE word indexer
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
Labels: Improvement, QA approved

#380 IBX-4031: Forced copy non-translatable field values from main content to current draft during publish
  eZ/Publish/Core/Repository/ContentService.php
  tests/integration/Core/Repository/ContentService/CopyNonTranslatableFieldsFromPublishedVersionTest.php
Labels: Bug, QA approved, Ready for MERGE
