Repository ezsystems/ezplatform-kernel, pull requests merged in 2023-03, with the labels that each got.

#363 IBX-3972: Fixed password validation for UserService::updateUserPassword
  eZ/Publish/API/Repository/Tests/PHPUnitConstraint/AllValidationErrorsOccur.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/Core/Repository/User/PasswordValidator.php
  eZ/Publish/Core/Repository/User/PasswordValidatorInterface.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/settings/fieldtype_services.yml
Labels: Bug, QA approved, Doc needed

#365 IBX-5026: Allowed user to move subtree if he doesn't have access to second content's location
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/ContentInfo.php
  eZ/Publish/Core/Repository/LocationService.php
Labels: Bug, QA approved, Ready for MERGE

#367 IBX-5270: Implemented cache indices validator and fixed broken `loadSubtreeIds` pattern
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/debug/cache_validator.yaml
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryPersistenceHandler.php
  eZ/Publish/Core/Persistence/Cache/InMemory/InMemoryCache.php
  eZ/Publish/Core/Persistence/Cache/PersistenceLogger.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
  src/lib/Persistence/Cache/CacheIndicesValidator.php
  src/lib/Persistence/Cache/CacheIndicesValidatorInterface.php
Labels: Improvement, QA approved

#364 IBX-5119: Added logging for invalid content's locations setup
  eZ/Publish/API/Repository/Values/Content/ContentInfo.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php
  eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
Labels: Improvement, QA approved
